-- Update exam table columns without dropping tables
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE exams MODIFY COLUMN qpId VARCHAR(200) NOT NULL;
ALTER TABLE exams MODIFY COLUMN batchId VARCHAR(200) NOT NULL;
ALTER TABLE exams MODIFY COLUMN courseId VARCHAR(200) NULL;

SET FOREIGN_KEY_CHECKS = 1;
